services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - shiba-network

  users-service:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
    networks:
      - shiba-network
    deploy:
      replicas: 1
    labels:
      app: users-service

  nginx:
    build:
      context: .
      dockerfile: Docker.nginx
    depends_on:
      - users-service
    image: nginx:latest
    container_name: nginx-service
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shiba-network

volumes:
  mongodb:

networks:
  shiba-network:
    driver: bridge
