apiVersion: v1
kind: Service
metadata:
  name: svc-users-service
  namespace: ns-shiba
spec:
  selector:
    name: p-users-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
